### ISSUE TITLE
fix tensorflow_backend to match keras tensorflow_backend

### ISSUE THREAD

**Issue by ahundt** [keras-team/keras-contrib#166]
keras-contrib unit tests are failing due to https://github.com/fchollet/keras/commit/6b106ab4ec9a1c0eb3e24ae590ce63f84022ad40 in keras, because the non-public backend functions have changed. We need to update the keras-contrib backend functions accordingly so they work in the same manner as keras. I'm making a quick fix at https://github.com/farizrahman4u/keras-contrib/pull/168. 
It looks like @farizrahman4u and @gvtulder have previously made changes in the relevant code, could one of you take a look?

Do we want to keep keras-contrib working with 2.0.8 as well?

**Comment by gabrieldemarmiesse** [comment]
This seems to have been fixed since all the tests are passing.
