### ISSUE TITLE
Travis error - mini conda scipy sparse

### ISSUE THREAD

**Issue by ahundt** [keras-team/keras-contrib#211]
Travis keeps encountering errors like the following:

```

==================================== ERRORS ====================================
___________ ERROR collecting tests/keras_contrib/constraints_test.py ___________
ImportError while importing test module '/home/travis/build/keras-team/keras-contrib/tests/keras_contrib/constraints_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/keras_contrib/constraints_test.py:5: in <module>
    from keras import backend as K
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/keras/__init__.py:3: in <module>
    from . import utils
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/keras/utils/__init__.py:25: in <module>
    from .training_utils import multi_gpu_model
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/keras/utils/training_utils.py:7: in <module>
    from ..layers.merge import concatenate
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/keras/layers/__init__.py:4: in <module>
    from ..engine import Layer
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/keras/engine/__init__.py:8: in <module>
    from .training import Model
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/keras/engine/training.py:11: in <module>
    from scipy.sparse import issparse
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/scipy/sparse/__init__.py:229: in <module>
    from .csr import *
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/scipy/sparse/csr.py:15: in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
E   ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so)
------------------------------- Captured stderr --------------------------------
```

https://api.travis-ci.org/v3/job/325623397/log.txt
Can anyone suggest a solution for this? I'm unable to reproduce it locally, and last I've checked the travis.yml is very to similar to the one in keras-team/keras/travis.yml.

**Comment by Dref360** [comment]
Should be keras_contrib instead of keras-contrib?
The path to the module seems wrong.

**Comment by ahundt** [comment]
The repository is keras-contrib while the import directory is keras_contrib, an unfortunate naming choice but I don't think it is the source of the problem. This really appears to be some form of incorrect versioning of the libstdc++  .so file imported for scipy.sparse...

**Comment by anand-sonawane** [comment]
There is a difference in the .travis.yml for keras and keras_contrib

keras : nose scipy matplotlib pandas pytest h5py
keras_contrib : scipy matplotlib pandas pytest h5py

Also,

After digging regarding this I found the following 2 links useful :+1: 
You can first try this : https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
and if this doesn't then check this commit by the tensorflow repo : They are just running travis test for python 2.7 for now .
https://github.com/tensorflow/tensorboard/commit/eced1910a5d3293c587d13eaba3348e51596e0c8

**Comment by ahundt** [comment]
@anand-sonawane cool, up for creating a PR to see if it works?

**Comment by anand-sonawane** [comment]
@ahundt so i fixed the travis issue 

Basically anaconda has out dated  libstdc++ library , so moved scipy from conda installations to pip installation,
Also, travis is failing due to a lot of errors in the CRF layer and had to ignore the test file for crf layer.

The PR is https://github.com/keras-team/keras-contrib/pull/217

**Comment by ahundt** [comment]
Merged!

**Comment by ahundt** [comment]
grumble grumble... [not quite out of the woods yet](https://travis-ci.org/keras-team/keras-contrib/jobs/336851037), apparently the curl command for downloading python 3.5 didn't work for one of the unit test modes...

I restarted the build, hopefully it will succeed.

**Comment by ahundt** [comment]
Passing now, thanks for the help!
