### ISSUE TITLE
create keras-contrib documentation website

### ISSUE THREAD

**Issue by ahundt** [keras-team/keras-contrib#220]
We would like help with generating a keras-team.github.io/keras-contrib equivalent to http://keras.io/.

**Comment by anand-sonawane** [comment]
@ahundt any idea where we can start? Would love to help

**Comment by ahundt** [comment]
I think the code to generate the docs for keras is called in the travis script:
https://github.com/keras-team/keras/blob/master/.travis.yml

At the bottom of https://keras.io the page says:

Built with MkDocs using a theme provided by Read the Docs. 
http://www.mkdocs.org/ 

So I guess check out the instructions there plus what's in travis to try and generate it?

**Comment by ahundt** [comment]
I found the actual docs generation code in keras:
https://github.com/keras-team/keras/tree/master/docs

I think the best approach would be to bring that into keras-contrib and adapt it for this repository.

**Comment by anand-sonawane** [comment]
I did some research and could create something similar to the keras documentation but need insights on how the autogen.py file in the docs folder is working. Could not understand where to exactly embed that file. 

I got the following output because I cant figure that out 
http://keras-contrib.readthedocs.io/en/latest/

**Comment by ahundt** [comment]
It looks like it defines a mapping between readme files and the classes that should go in them. Probably most of the stuff like the following would be deleted:
```
    {
        'page': 'layers/merge.md',
        'classes': [
            layers.Add,
            layers.Subtract,
            layers.Multiply,
            layers.Average,
            layers.Maximum,
            layers.Concatenate,
            layers.Dot,
        ],
```

Then it can all be replaced with the items that actually exist here in keras-contrib.

**Comment by Balance-Breaker** [comment]
@ahundt I would like to work on this issue.But I think first markdown documentation is required. For that can I open another issue regarding documentation and start contributing for the same.

**Comment by ahundt** [comment]
Sounds awesome, thanks!
