### ISSUE TITLE
Shape error when using CRF for binary segmentation

### ISSUE THREAD

**Issue by LambertMark** [keras-team/keras-contrib#265]
I am trying to apply a CRF layer to my network for binary segmentation, but it is resulting in an error: 

> `ValueError: Shapes (?, 1, 1) and (?, 336, 1) are not compatible.`

I want to output a tensor with the shape (batch_size, 224, 336, 1). Based on the error, the img_height appears to have been lost once the CRF was introduced.

I am using Keras 2.1.5 with the tensorflow backend on python 3.5.

Below is some sample code describing my model. Without the CRF at the end it works without problems.

```
import keras
from keras.layers import UpSampling2D, Conv2D, Activation, MaxPooling2D
from keras_contrib.layers import CRF

img_width, img_height = 336, 224
kernel_size = 7

input=keras.engine.topology.Input(shape=(img_height, img_width, 3))

e=Conv2D(32,(kernel_size,kernel_size),padding='same')(input)
e=Activation('relu')(e)
e=MaxPooling2D(pool_size=(2, 2))(e)

e=Conv2D(64,(kernel_size,kernel_size),padding='same')(e)
e=Activation('relu')(e)
e=MaxPooling2D(pool_size=(2, 2))(e)

#Decoder layers
d=UpSampling2D()(e)
d=Conv2D(64,(kernel_size,kernel_size),padding='same')(d)
d=Activation('relu')(d)

d=UpSampling2D()(d)
d=Conv2D(32,(kernel_size,kernel_size),padding='same')(d)
d=Activation('relu')(d)

d=Conv2D(1,(1,1),padding='valid')(d)
d=Activation('sigmoid')(d)

out=CRF(1, sparse_target=True)(d) 

model = Model(inputs=input, outputs=out)
```
What is the correct way to add the CRF to my segmentation network?

**Comment by linxihui** [comment]
@LambertMark  CRF only supports sequential data, NOT spatial data. Thus the input should be 3D inputs,  i.e., `(batch_size, seq_len, features)`.

**Comment by LambertMark** [comment]
That explains it.  I want to use the CRF as a way to improve image segmentation results like in [this DeepLab paper.](https://ieeexplore.ieee.org/abstract/document/7913730/)  Is there another CRF package for keras that can do something like this?

**Comment by LambertMark** [comment]
I was able to do segmentation with spatial data by adapting [this guide](http://warmspringwinds.github.io/tensorflow/tf-slim/2016/12/18/image-segmentation-with-tensorflow-using-cnns-and-conditional-random-fields/) for keras.  Closing issue.
