### ISSUE TITLE
How would you add keras-contrib as a dependency to setup.py?

### ISSUE THREAD

**Issue by JohnGiorgi** [keras-team/keras-contrib#299]
I don't know if this is the best place to ask this, but I cannot seem to figure it out.

I want to add `keras-contrib` to my `setup.py` as a dependency. The accepted answer on [this](https://stackoverflow.com/a/32689886) Stackoverflow post gets me part of the way there.

I guess the idea is to structure `setup.py` like so:

```python
import setuptools

setuptools.setup(
    ...
    install_requires=['keras-contrib']
    ...
    dependency_links=['https://www.github.com/keras-team/keras-contrib/tarball/master#egg=keras-contrib']
    ...
)
```

However, calling `pip install -e .` from the directory where `setup.py` just results in the following:

```bash
Collecting keras-contrib (from test==0.0.1)
  Could not find a version that satisfies the requirement keras-contrib (from Saber==0.9.4) (from versions: )
No matching distribution found for keras-contrib (from test==0.0.1)
```

Oddly enough, I can add `keras-contrib` as a dependency in a `requirments.txt` file without issue using:

```
git+https://www.github.com/keras-team/keras-contrib.git
```

Has anyone else been able to add `keras-contrib` as a dependency? Is this even possible?

**Comment by 2martens** [comment]
Maybe you should use keras_contrib?

**Comment by MFreidank** [comment]
I believe you only need the dependency in the `dependency_links` list, you can drop the `install_requires` dependency and everything should work.

**Comment by JohnGiorgi** [comment]
@MFreidank 

I've tried all combinations of using `install_requires` and `dependency_links`. But just to be sure, I tried your suggestion. As far as I can tell, it doesn't work.

```python
import setuptools

setuptools.setup(
    ...
    install_requires=[]
    ...
    dependency_links=['https://www.github.com/keras-team/keras-contrib/tarball/master#egg=keras-contrib']
    # I saw this pattern on a different GitHub repo, but it doesn't seem to work either!
    # dependency_links=['git+https://www.github.com/keras-team/keras.git#egg=keras-contrib-2.0.8'],
    ...
)
```

**Comment by MFreidank** [comment]
A minor variation of your second line works for me:
`    setup(
        name=NAME,
        install_requires=["keras-contrib",],
        dependency_links=['git+https://github.com/keras-team/keras-contrib.git/@master#egg=keras-contrib']
    )
`

**Comment by JohnGiorgi** [comment]
Very weird, 

neither 

```python
import setuptools

setuptools.setup(
    ...
    install_requires=[]
    ...
    dependency_links=['git+https://github.com/keras-team/keras-contrib.git/@master#egg=keras-contrib']
    ...
)
```

nor

```python
import setuptools

setuptools.setup(
    ...
    install_requires=['keras-contrib']
    ...
    dependency_links=['git+https://github.com/keras-team/keras-contrib.git/@master#egg=keras-contrib']
    ...
)
```

work for me.

The former runs without any error, but doesn't install `keras-contrib`. The latter fails with the following error:

```
Could not find a version that satisfies the requirement keras-contrib (from versions: )
No matching distribution found for keras-contrib
```

**Comment by 2martens** [comment]
I write it again: What happens if you try keras_contrib whereever the package name is required? The underscore is there on purpose.

**Comment by JohnGiorgi** [comment]
@2martens 

I do not know what you mean?

Do you mean using `keras_contrib` instead of `keras-contrib`? Because that doesn't work:

`Could not find a version that satisfies the requirement keras_contrib`

**Comment by 2martens** [comment]
I am using:
```python
install_requires=["keras>=2.1.4", "keras_contrib"],
dependency_links=["https://github.com/keras-team/keras-contrib/tarball/master#egg=keras_contrib"],
```
And the installation with ``pip install -e .`` works without a problem.

**Comment by JohnGiorgi** [comment]
@2martens 

Okay. I created a simple `setup.py` file that looks exactly like this:

```python
import setuptools

setuptools.setup(
    name="test",
    install_requires=[
        "keras>=2.1.4", 
        "keras_contrib"
    ],
    dependency_links=["https://github.com/keras-team/keras-contrib/tarball/master#egg=keras_contrib"],
)
```

Just like you say. Then, from the same directory I run `pip install -e .`. Still no luck, I get:

```
Collecting keras>=2.1.4 (from test==0.0.0)
  Using cached https://files.pythonhosted.org/packages/34/7d/b1dedde8af99bd82f20ed7e9697aac0597de3049b1f786aa2aac3b9bd4da/Keras-2.2.2-py2.py3-none-any.whl
Collecting keras_contrib (from test==0.0.0)
  Could not find a version that satisfies the requirement keras_contrib (from test==0.0.0) (from versions: )
No matching distribution found for keras_contrib (from test==0.0.0)
```

I don't have a clue why this would work for you but not me.

**Comment by 2martens** [comment]
I am using Python 3.5. Are you using also Python 3. If yes than I have no idea.

**Comment by JohnGiorgi** [comment]
Yup. Python 3.6

**Comment by gabrieldemarmiesse** [comment]
Closing now, for the V1.0 of keras contrib, we'll upload it to pypi. It should be much easier to declare as a dependancy.
