### ISSUE TITLE
recent commit to master branch breaks CRF layer

### ISSUE THREAD

**Issue by Zen3515** [keras-team/keras-contrib#422]
This code can be run with keras-contrib 2 hrs ago, but recently, with the new commit this code no longer work.
Here, take a look.

**Please note that I use tensorflow backend**

`model = Sequential()
model.add(Embedding(len(word_to_idx),32,input_length=102,mask_zero=True, trainable=True))
model.add(Bidirectional(GRU(32, return_sequences=True)))
model.add(Dropout(0.2))
model.add(TimeDistributed(Dense(n_classes,activation='softmax')))
crf = CRF(n_classes, sparse_target=False, learn_mode='join', test_mode='viterbi')
model.add(crf)
model.summary()
adam  = Adam(lr=0.001)
model.compile(optimizer=adam,  loss=crf_nll, metrics=[crf_viterbi_accuracy])`

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-dae03fef15ed> in <module>()
      6 model.add(TimeDistributed(Dense(n_classes,activation='softmax')))
      7 crf = CRF(n_classes, sparse_target=False, learn_mode='join', test_mode='viterbi')
----> 8 model.add(crf)
      9 model.summary()
     10 adam  = Adam(lr=0.001)

/usr/local/lib/python3.5/site-packages/keras/models.py in add(self, layer)
    520                           output_shapes=[self.outputs[0]._keras_shape])
    521         else:
--> 522             output_tensor = layer(self.outputs[0])
    523             if isinstance(output_tensor, list):
    524                 raise TypeError('All layers in a Sequential model '

/usr/local/lib/python3.5/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    617 
    618             # Actually call the layer, collecting output(s), mask(s), and shape(s).
--> 619             output = self.call(inputs, **kwargs)
    620             output_mask = self.compute_mask(inputs, previous_mask)
    621 

/usr/local/lib/python3.5/site-packages/keras_contrib/layers/crf.py in call(self, X, mask)
    288 
    289         if self.test_mode == 'viterbi':
--> 290             test_output = self.viterbi_decoding(X, mask)
    291         else:
    292             test_output = self.get_marginal_prob(X, mask)

/usr/local/lib/python3.5/site-packages/keras_contrib/layers/crf.py in viterbi_decoding(self, X, mask)
    560                 input_energy, mask, self.left_boundary, self.right_boundary)
    561 
--> 562         argmin_tables = self.recursion(input_energy, mask, return_logZ=False)
    563         argmin_tables = K.cast(argmin_tables, 'int32')
    564 

/usr/local/lib/python3.5/site-packages/keras_contrib/layers/crf.py in recursion(self, input_energy, mask, go_backwards, return_sequences, return_logZ, input_length)
    523                                                    constants=constants,
    524                                                    input_length=input_length,
--> 525                                                    unroll=self.unroll)
    526 
    527         if return_sequences:

/usr/local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in rnn(step_function, inputs, initial_states, go_backwards, mask, constants, unroll, input_length)
   2684 
   2685         time_steps = tf.shape(inputs)[0]
-> 2686         outputs, _ = step_function(inputs[0], initial_states + constants)
   2687         output_ta = tensor_array_ops.TensorArray(
   2688             dtype=outputs.dtype,

/usr/local/lib/python3.5/site-packages/keras_contrib/layers/crf.py in _step(input_energy_i, states)
    517 
    518         def _step(input_energy_i, states):
--> 519             return self.step(input_energy_i, states, return_logZ)
    520 
    521         target_val_last, target_val_seq, _ = K.rnn(_step, input_energy,

/usr/local/lib/python3.5/site-packages/keras_contrib/layers/crf.py in step(self, input_energy_t, states, return_logZ)
    459                 m = states[3][:, t:(t + 2)]
    460             else:
--> 461                 m = K.slice(states[3], [0, t], [-1, 2])
    462             input_energy_t = input_energy_t * K.expand_dims(m[:, 0])
    463             # (1, F, F)*(B, 1, 1) -> (B, F, F)

AttributeError: module 'keras.backend' has no attribute 'slice'

**Comment by gabrieldemarmiesse** [comment]
Thanks for this *insanely fast* report. Let me fix it right now.

**Comment by Zen3515** [comment]
Oh, sorry, I was using **Keras 2.1.6**.
I was a little panic, anyways, thank you.

**Comment by gabrieldemarmiesse** [comment]
no problem! I glad it's solved.

**Comment by renukaik** [comment]
I am facing the same issue, even with Keras 2.4.0 or 2.4.3 issue is not getting resolved. What should be the version of TensorFlow (should be >2.2) and Keras I should use.
