### ISSUE TITLE
ImportError :  cannot import name "InstanceNormalization"

### ISSUE THREAD

**Issue by nobodykid** [keras-team/keras-contrib#466]
Hello, it seems that I have problem in importing one of the module. Currently I'm using keras_contrib `0.0.2` and keras `2.2.2`.

When I tried importing `InstanceNormalization`, I got this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'InstanceNormalization'
```
I tried running a Jupyter notebook to see if the code completion can catch it after I imported `keras_contrib`. And this code is what I got
```
from keras_contrib.layers.normalization import instancenormalization
```
But I'm unable to call the method in my code (when I'm tried to build a layer for GAN)

Is there something wrong with my installation/setting? I used the same install instruction as in README

Side note : even though I'm not able to import  `InstanceNormalization`, I'm able to import  `DSSIMObjective`. I haven't tested on another functions

**Comment by e-yi** [comment]
In case someone needs a quick fix
currently I (1) removed ```from .normalization import InstanceNormalization
from .normalization import GroupNormalization``` from keras_contrib\layers\__init__.py, (2) redo `python setup.py install` and (3) copy the normalizaiton files directly into project folder and import the files later to fix this problem temporarily. 
It works for me.

**Comment by b-z** [comment]
+1

**Comment by nobodykid** [comment]
I fixed the problem

It seems that I have to add `instancenormalization`, resulting the import code into
```
from keras_contrib.layers.normalization.instancenormalization import InstanceNormalization
```
`normalization` still contains several scripts, like `instancenormalization` and `groupnormalization`. So you have to specify it until you get the `instancenormalization.py` in your import

**Comment by b-z** [comment]
Works for me. Thanks.

**Comment by nobodykid** [comment]
No problem @b-z, I'm closing this issue now

**Comment by SophieZhou** [comment]
Works for me. Thanks very much.
