### ISSUE TITLE
Bilstm + CRF on top

### ISSUE THREAD

**Issue by Athaagra** [keras-team/keras-contrib#467]
I am facing an error when i user crf out it gives me an attribute error:
AttributeError: module ‘keras.backend’ has no attribute ‘slice’
Keras version:2.1.2
Kera contrib:2.0.8
Tf version:1.8.0

**Comment by RaphaelMeudec** [comment]
@Athaagra Could you provide a sample script to reproduce the error and the full stacktrace? Thanks

**Comment by Athaagra** [comment]
@RaphaelMeudec  i manage to make it work using the 
Keras version: 2.2.2

**Comment by xqtbox** [comment]
I upgrade keras version to 2.2.4 can solve this problem

**Comment by RaphaelMeudec** [comment]
@Athaagra Cool! Can you close the issue?
