### ISSUE TITLE
The added layer must be an instance of class Layer. Found: <keras_contrib.layers.crf.CRF object at 0x12bfa4550>

### ISSUE THREAD

**Issue by StevenChaoo** [keras-team/keras-contrib#492]
Hi,
I just can't add the crf layer.
Env: python=3.7, tensorflow=1.13.1, keras=2.2.4, tf-keras-contrib=2.0.8

```
import numpy as np
from keras import backend as K
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, Bidirectional, LSTM, Dense, TimeDistributed, Dropout
from keras_contrib.layers import CRF
import matplotlib.pyplot as plt
import os

def tokenvec_bilstm2_crf_model():
    model = Sequential()
    crf_layer = CRF(10, sparse_target=True)
    print(crf_layer)
    model.add(crf_layer)
    model.compile('adam', loss=crf_layer.loss_function, metrics=[crf_layer.accuracy])
    model.summary()
    return model

if __name__ == '__main__':
    tokenvec_bilstm2_crf_model()
```

my wrong is :
`Exception has occurred: TypeError
The added layer must be an instance of class Layer. Found: <keras_contrib.layers.crf.CRF object at 0x129de8668>
  File "/Users/steven/Desktop/MedicalNamedEntityRecognition/TEST.py", line 20, in tokenvec_bilstm2_crf_model
    model.add(crf_layer)
  File "/Users/steven/Desktop/MedicalNamedEntityRecognition/TEST.py", line 30, in <module>
    tokenvec_bilstm2_crf_model()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)`

**Comment by OKtang** [comment]
请问你解决这个问题了吗？

**Comment by StevenChaoo** [comment]
python版本从3.7换到3.6.2 tensorflow换到1.8（？）解决了

发自我的 iPhone

在 2019年6月18日，11:26，OKtang <notifications@github.com<mailto:notifications@github.com>> 写道：


请问你解决这个问题了吗？
